// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKlO80bcEp5XlfeGD9Iwis6UAyvw1ecdk',
    appId: '1:526331216604:web:c3980ac3526c748e442a19',
    messagingSenderId: '526331216604',
    projectId: 'diuclubs',
    authDomain: 'diuclubs.firebaseapp.com',
    storageBucket: 'diuclubs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4AKd9PdYQmIyh5BkAevaZ_bx9ggsxWAQ',
    appId: '1:526331216604:android:4de6354db30636f2442a19',
    messagingSenderId: '526331216604',
    projectId: 'diuclubs',
    storageBucket: 'diuclubs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDpWTPKIe1NKc2dF99KHF-OajuyMttxVM',
    appId: '1:526331216604:ios:54e511e55baf8dd0442a19',
    messagingSenderId: '526331216604',
    projectId: 'diuclubs',
    storageBucket: 'diuclubs.appspot.com',
    iosBundleId: 'com.example.diu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDpWTPKIe1NKc2dF99KHF-OajuyMttxVM',
    appId: '1:526331216604:ios:062fd592ae8986bc442a19',
    messagingSenderId: '526331216604',
    projectId: 'diuclubs',
    storageBucket: 'diuclubs.appspot.com',
    iosBundleId: 'com.example.diu.RunnerTests',
  );
}
